### PR TITLE
fix: remove pindel decompose and update filters

### PR DESCRIPTION
**Pull request by elleira**

### CODE REVIEW

**Comment by maehler** [comment]
Sorry for sleeping on this. I started to set up our environment to be able to test things properly, but it turned out to take some time. I'll do a proper review once I have everything set up!

**Comment by elleira** [comment]
No stress!  Things got delayed here as well so I'm not working on it as much right now

**Comment by elleira** [comment]
Aaa so i apparently only have the line in my local config, sorry! 
So in the `config.yaml` under `svdb_query` you need to set the `--out_frq` and `--out_occ` as well as the --db.
```
svdb_query:
  db_string: "--db ReferencePools/240702/reference_files/svdb_cnv.vcf --out_frq Normal_AF --out_occ Normal_240702" 
```

I set out_occ to just Normal and the date i created the normal panel, and then the out_frq Normal_AF since it will be the same regardless which (version of the) panel you use and you wont have to edit the filters each time you update the normal panel.

**Comment by maehler** [comment]
Ok, that explains it! Could it be an option to set the default `db_string` to something like `"--db FILL_ME_IN --out_frq Normal_AF --out_occ Normal"`?

**Comment by elleira** [comment]
> Ok, that explains it! Could it be an option to set the default `db_string` to something like `"--db FILL_ME_IN --out_frq Normal_AF --out_occ Normal_OCC"`?

Added!

**Comment by maehler** [comment]
I ran into a similar error now for a different filter. It's trying to use `FORMAT:DP`, but my input files have this annotation in the INFO field.

https://github.com/genomic-medicine-sweden/poppy/blob/0f147064a36c4133e499a6c4bc34052c06763056/config/config_hard_filter_somatic.yaml#L6-L9

The input file is `cnv_sv/pindel_vcf/{sample}_{type}.no_tc.normalized.vep_annotated.filter.somatic_hard.vcf.gz`. How does this look for you?

**Comment by maehler** [comment]
Is it simply that `artifact_annotated` has to be added to the pindel output file? This is currently missing from the filename in the default `config/output_files.yaml`.

**Comment by elleira** [comment]
Yes sorry! The whole thing of having double configs and stressing to get things done before vacation really helps with not missing stuff :sweat_smile:  
So yes, the file should be artifact annotated before the pindelfilter, so the filter input should be:
`"cnv_sv/pindel_vcf/{sample}_{type}.no_tc.vep_annotated.artifact_annotated.vcf.gz"`

**Comment by maehler** [comment]
Just running a last test on our side as a sanity check. After that I see no reason to not merge this.

**Review by maehler — APPROVED** [review]
I haven't really looked at the results, but everything runs now, so I say merge. Nice work!

**Pull request merged**
